app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopping/', include('shoppingList.urls')),
    path('', include('member.urls')),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

app/member/urls.py
from django.urls import path

from member.views import signup_view, login_view, logout_view

app_name = 'members'
urlpatterns = [
    path('', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

app/shoppingList/urls.py
from django.urls import path

from shoppingList.views import shoppingList

app_name = 'shop'
urlpatterns = [
    path('shoppinglist/', shoppingList, name="shopping-list"),
    # path('all_items/<str:keyword>/', data_crawler, name='data')
]

app/member/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    name = models.CharField(max_length=50, blank=True)

app/shoppingList/models.py
from django.db import models


# Create your models here.
from member.models import User


class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100)
    item_original_price = models.CharField(max_length=100, blank=True)
    item_discount_price = models.CharField(max_length=100, blank=True)
    item_discount_rate = models.CharField(max_length=100, blank=True)
    item_image = models.ImageField(blank=True)

    def __str__(self):
        return self.item_name, self.item_original_price, self.item_discount_price

app/member/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from django.core.exceptions import ValidationError

from member.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label="사용자 아이디", widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'placeholder': '아이디'
        }))
    password = forms.CharField(label='사용자 비밀번호', widget=forms.PasswordInput(
        attrs={
            'class': 'form-input',
            'placeholder': '비밀번호'
        }
    ))

    # is_valid() 호출시 clean() 자동 호출. clean() 함수를 오버라이딩
    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if not user:
            raise ValidationError("아이디 혹은 비밀번호를 잘못 입력하셨습니다.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(request, username=username, password=password)
        login(request, user)


class SignupForm(forms.Form):
    username = forms.CharField(
        label='사용자 아이디',
        widget=forms.TextInput(
            attrs={
                'class': 'username-field',
                'placeholder': '아이디',
            }
        ))
    password = forms.CharField(
        label='사용자 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'password-field',
                'placeholder': '비밀번호',
            }
        ))
    email = forms.EmailField(
        label='사용자 이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'email-field',
                'placeholder': '이메일',
            }
        ))
    name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'name-field',
                'placeholder': '이름',
            }
        ))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError('이미 사용중인 username입니다')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('이미 사용중인 email입니다')
        return email

    def save(self):
        User.objects.create_user(
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password'],
            email=self.cleaned_data['email'],
            name=self.cleaned_data['name']
        )

app/member/views.py
# Create your views here.
from django.contrib.auth import logout, login
from django.shortcuts import render, redirect
from member.forms import LoginForm, SignupForm


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            form.login(request)
            return redirect('shop:shopping-list')
    else:
        form = LoginForm()
    print(request.user)
    context = {
        'loginForm': form
    }
    return render(request, 'members/login.html', context)


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('shop:shopping-list')
    else:
        form = SignupForm()
    context = {
        'signupForm': form
    }
    return render(request, 'members/signup.html', context)


def logout_view(request):
    logout(request)
    return redirect('members:login')

app/shoppingList/views.py
from django.shortcuts import render, redirect

from shoppingList.crawler import data_crawler
from shoppingList.models import Item


def shoppingList(request):
    if request.method == 'POST':
        item = Item.objects.all()
        if item:
            Item.objects.all().delete()
        data_crawler(request, user=request.user, keyword=request.POST['keyword'])

        return redirect('shop:shopping-list')
    else:
        items = Item.objects.all()
    if request.user.is_authenticated:
        context = {
            'items': items
        }
        return render(request, 'shop/shoppingList.html', context)
    else:
        return redirect('members:login')

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block head %}
    {% endblock %}
</head>
<body>
<div>
</div>
<div id="wrap">
    {% block content %}{% endblock %}
</div>
</body>
</html>

app/templates/members/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h3 class="title">Login Form</h3>
    <div class="form-wrapper">
        {% if loginForm.non_field_errors %}
            <ul class="error-list">
                {% for error in loginForm.non_field_errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in loginForm %}
                <div class="form-field-wrapper">
                    {{ field }}
                </div>
            {% endfor %}




            <div class="form-button-wrapper">
                <button type="submit">로그인</button>
            </div>
        </form>
    </div>
    <div class="signup-link">
        <a href="{% url 'members:signup' %}">회원가입 페이지</a>
    </div>
{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h3 class="title">Singup Form</h3>
    <div class="form-wrapper">
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in signupForm %}
            <div class="form-field-wrapper">
                {{ field }}
            </div>
                {% if field.errors %}
                    <ul class="error-list">
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endfor %}
            <div class="form-button-wrapper">
                <button type="submit">회원가입</button>
            </div>
        </form>
    </div>
    <div class="login-link">
        <a href="{% url 'members:login' %}">로그인 페이지</a>
    </div>
{% endblock %}

app/templates/shop/shoppingDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>쇼핑 디테일</div>
</body>
</html>

app/templates/shop/shoppingList.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <div class="shopping-title"><a href="{% url 'members:logout' %}">로그아웃</a></div>
        <div class="shopping-title">{{ request.user }}</div>
        <div class="shopping-title">{{ request.user.is_authenticated }}</div>

        <form action="{% url 'shop:shopping-list' %}" method="POST">
            {% csrf_token %}
            <h3 class="shopping-title"> 검색하고자 하는 상품을 입력해 주세요:</h3>
            <div class="form__group">
                <input class="form__field" type="text" name="keyword" placeholder="키워드를 입력해 주세요" required/>
                <label class="form__label">키워드</label>
            </div>
            <div class="button__group">
                <button class="form__button">검색</button>
            </div>

        </form>

        {% load el_pagination_tags %}
        {% paginate items %}
        {% for item in items %}
            <div class="item-wrapper">
                <div>
                    <label class="item-wrapper-label">상품 이름: </label>
                    <p class="item-wrapper-info">{{ item.item_name }}</p>
                </div>

                {% if item.item_discount_rate %}
                    <div>
                        <label class="item-wrapper-label">할인률: </label>
                        <p class="item-wrapper-info">{{ item.item_discount_rate }}</p>
                    </div>
                {% else %}
                    <div>
                        <label class="item-wrapper-label">할인률:</label>
                        <p class="item-wrapper-info">0%</p>
                    </div>
                {% endif %}


                <div>
                    <label class="item-wrapper-label">원가: </label>
                    <p class="item-wrapper-info">{{ item.item_original_price }}</p>
                </div>


                {% if item.item_discount_price %}
                    <div>
                        <label class="item-wrapper-label">할인가: </label>
                        <p class="item-wrapper-info">{{ item.item_discount_price }}</p>
                    </div>
                {% else %}
                    <div>
                        <label class="item-wrapper-label">할인가: </label>
                        <p class="item-wrapper-info">없음</p>
                    </div>
                {% endif %}

            </div>
        {% endfor %}
        <div class="pagination-wrapper item-wrapper">
        {% show_pages %}
        </div>

    </div>
{% endblock %}